# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\home.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import globals

import sys
sys.path.insert(1, 'src/pgp')
import PGP
sys.path.append('..')

class Ui_Form(object):

    


    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(250, 20, 281, 50))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(180, 100, 421, 441))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.button_handler_private_key_ring)
        self.verticalLayout.addWidget(self.pushButton_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.pushButton_4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(self.button_handler_recieveMessage)
        self.verticalLayout.addWidget(self.pushButton_4)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):

        globals.algoAsymEncryption = None
        globals.algoAsymSignature = None
        globals.algoSym = None
        globals.message = ""
        globals.filePath = ""
        globals.email = ""
        globals.privateKeyEntry = None
        globals.publicKeyEntry = None
        globals.previousRowPrivate = None
        globals.previousRowPublic = None
        globals.pgpOptions = PGP.PGPOptions()


        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "PGP"))
        self.pushButton.setText(_translate("Form", "Public Key Ring"))
        self.pushButton.clicked.connect(self.button_handler_public_key_ring)
        self.pushButton_2.setText(_translate("Form", "Private Key Ring"))
        self.pushButton_3.setText(_translate("Form", "Send Message"))
        self.pushButton_3.clicked.connect(self.button_handler_sendMessage)

        self.pushButton_4.setText(_translate("Form", "Receive Message"))

    def button_handler_sendMessage(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = sendMessage1UI()
        self.ui.setupUi(self.window)
        globals.currentWindow.hide()
        globals.currentWindow = self.window
        self.window.show()

    def button_handler_public_key_ring(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = publicKeyRingUI()
        self.ui.setupUi(self.window)
        globals.currentWindow.hide()
        globals.currentWindow = self.window
        self.window.show()

    def button_handler_private_key_ring(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = privateKeyRingUI()
        self.ui.setupUi(self.window)
        globals.currentWindow.hide()
        globals.currentWindow = self.window
        self.window.show()

    def button_handler_recieveMessage(self):
        self.window = QtWidgets.QMainWindow()
        filePath, enteredFileName = QtWidgets.QInputDialog.getText(globals.currentWindow, 'File Path', 'Enter file path:')
        if enteredFileName:
            pgpOptions = globals.pgp.checkPGPOptions(filePath)
            password = None
            if pgpOptions.encryption:
                password, enteredPassword = QtWidgets.QInputDialog.getText(globals.currentWindow, 'Password', 'Enter password:')
                if not enteredPassword:
                    msg = QMessageBox(globals.currentWindow)
                    msg.setWindowTitle("PASSWORD ERROR!")
                    msg.setText("PASSWORD REQUIRED!")
                    msg.exec()
                    return
            try:
                recievedMessage,email = globals.pgp.receiveMessage(filePath=filePath, password=password)
                recievedMessage = recievedMessage.decode('utf-8')
                globals.message = recievedMessage
                globals.pgpOptions = pgpOptions
                globals.email = email 
                self.ui = messageRecieveUI()
                self.ui.setupUi(self.window)
                globals.currentWindow.hide()
                globals.currentWindow = self.window
                self.window.show()
            except Exception as e:
                msg = QMessageBox(globals.currentWindow)
                msg.setWindowTitle("ERROR!")
                msg.setText(str(e))
                msg.exec()
                return



from sendMessage1 import Ui_Form as sendMessage1UI
from publicKeyRing import Ui_publicKeyRing as publicKeyRingUI
from privateKeyRing import Ui_privateKeyRing as privateKeyRingUI
from messageRecieve import Ui_Form as messageRecieveUI