# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\sendMessage1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import globals
from PyQt5.QtWidgets import QDialog, QDialogButtonBox, QVBoxLayout, QLabel

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(660, 540, 120, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(250, 60, 321, 51))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(20, 540, 120, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(120, 150, 591, 251))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox_4 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_4.setObjectName("checkBox_4")
        self.horizontalLayout.addWidget(self.checkBox_4)
        self.checkBox_3 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout.addWidget(self.checkBox_3)
        self.checkBox_2 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout.addWidget(self.checkBox_2)
        self.checkBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout.addWidget(self.checkBox)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.textEdit_2 = QtWidgets.QTextEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_2.sizePolicy().hasHeightForWidth())
        self.textEdit_2.setSizePolicy(sizePolicy)
        self.textEdit_2.setMinimumSize(QtCore.QSize(0, 25))
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout.addWidget(self.textEdit_2)
        self.gridLayout.addLayout(self.verticalLayout, 3, 1, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_2.setText(_translate("Form", "Next"))
        self.pushButton_2.clicked.connect(self.button_handler_sendMessageNext)
        self.label.setText(_translate("Form", "Send Message"))
        self.pushButton.setText(_translate("Form", "Back"))
        self.pushButton.clicked.connect(self.button_handler_sendMessageBack)
        self.checkBox_4.setText(_translate("Form", "Signature"))
        self.checkBox_3.setText(_translate("Form", "Zip"))
        self.checkBox_2.setText(_translate("Form", "Encryprion"))
        self.checkBox.setText(_translate("Form", "Radix64"))
        self.label_3.setText(_translate("Form", "Options"))
        self.label_4.setText(_translate("Form", "File Path"))
        self.label_2.setText(_translate("Form", "Message Text"))
        self.textEdit.setText(globals.message)
        self.textEdit_2.setText(globals.filePath)
        self.checkBox_2.setChecked(globals.pgpOptions.encryption)
        self.checkBox.setChecked(globals.pgpOptions.radix64)
        self.checkBox_3.setChecked(globals.pgpOptions.zip)
        self.checkBox_4.setChecked(globals.pgpOptions.signature)

    def button_handler_sendMessageBack(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = homeUI()
        self.ui.setupUi(self.window)
        globals.currentWindow.hide()
        globals.currentWindow = self.window
        self.window.show()

    def button_handler_sendMessageNext(self):
        globals.pgpOptions.signature = self.checkBox_4.isChecked()
        globals.pgpOptions.zip = self.checkBox_3.isChecked()
        globals.pgpOptions.encryption = self.checkBox_2.isChecked()
        globals.pgpOptions.radix64 = self.checkBox.isChecked()
        globals.message = self.textEdit.toPlainText()
        globals.filePath = self.textEdit_2.toPlainText()
        if globals.filePath != "":
            if globals.pgpOptions.encryption or globals.pgpOptions.signature:
                self.window = QtWidgets.QMainWindow()
                self.ui = algoChoiceUI()
                self.ui.setupUi(self.window)
                globals.currentWindow.hide()
                globals.currentWindow = self.window
                self.window.show()
            else:
                self.window = QtWidgets.QMainWindow()
                self.ui = summaryUI()
                self.ui.setupUi(self.window)
                globals.currentWindow.hide()
                globals.currentWindow = self.window
                self.window.show()
        else:
            dlg = QDialog(globals.currentWindow)
            dlg.setWindowTitle("FILE PATH ERROR!")
            QBtn = QDialogButtonBox.Ok | QDialogButtonBox.Cancel
            dlg.buttonBox = QDialogButtonBox(QBtn)
            dlg.buttonBox.accepted.connect(dlg.accept)
            dlg.buttonBox.rejected.connect(dlg.reject)
            dlg.layout = QVBoxLayout()
            message = QLabel("PLEASE ENTER FILE PATH!")
            dlg.layout.addWidget(message)
            dlg.layout.addWidget(dlg.buttonBox)
            dlg.setLayout(dlg.layout)
            dlg.exec()


from home import Ui_Form as homeUI
from algorithmChoice import Ui_AlgorithmForm as algoChoiceUI
from summaryPage import Ui_summaryPage as summaryUI