# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\summaryPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog, QDialogButtonBox, QVBoxLayout, QLabel
import globals

class Ui_summaryPage(object):
    def setupUi(self, summaryPage):
        summaryPage.setObjectName("summaryPage")
        summaryPage.resize(800, 300)
        self.label = QtWidgets.QLabel(summaryPage)
        self.label.setGeometry(QtCore.QRect(30, 20, 141, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(summaryPage)
        self.textBrowser.setGeometry(QtCore.QRect(30, 80, 741, 100))
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton_3 = QtWidgets.QPushButton(summaryPage)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 240, 120, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_2 = QtWidgets.QPushButton(summaryPage)
        self.pushButton_2.setGeometry(QtCore.QRect(660, 240, 120, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(summaryPage)
        QtCore.QMetaObject.connectSlotsByName(summaryPage)

    def retranslateUi(self, summaryPage):
        _translate = QtCore.QCoreApplication.translate
        summaryPage.setWindowTitle(_translate("summaryPage", "Form"))
        self.label.setText(_translate("summaryPage", "Message:"))
        self.pushButton_3.setText(_translate("summaryPage", "Back"))
        self.pushButton_3.clicked.connect(self.button_handler_back)
        self.pushButton_2.setText(_translate("summaryPage", "Send"))
        self.pushButton_2.clicked.connect(self.button_handler_send)

        self.textBrowser.setText(globals.message)


    def button_handler_back(self):
        self.window = QtWidgets.QMainWindow()
        if globals.pgpOptions.encryption or globals.pgpOptions.signature:      
            self.ui = keySelectionUI()
        else:
            self.ui = sendMessageUI()

        self.ui.setupUi(self.window)
        globals.currentWindow.hide()
        globals.currentWindow = self.window
        self.window.show()


    def button_handler_send(self):
        enteredPassword = True
        password = ""
        self.window = QtWidgets.QMainWindow()
        if globals.pgpOptions.signature:
            password,enteredPassword = QtWidgets.QInputDialog.getText(
            globals.currentWindow, 'Password', 'Enter password:')
        dlg = QDialog(globals.currentWindow)
        QBtn = QDialogButtonBox.Ok | QDialogButtonBox.Cancel
        dlg.buttonBox = QDialogButtonBox(QBtn)
        dlg.buttonBox.accepted.connect(dlg.accept)
        dlg.buttonBox.rejected.connect(dlg.reject)
        dlg.layout = QVBoxLayout()
        if enteredPassword:
            try:
                globals.pgp.sendMessage(message=bytes(globals.message, 'utf-8'), filePath=globals.filePath, pgpoptions=globals.pgpOptions, algotTypeSym=globals.algoSym, privateKeyEntry=globals.privateKeyEntry, password=password, publicKeyEntry=globals.publicKeyEntry)
                self.ui = homeUI()
                self.ui.setupUi(self.window)
                globals.currentWindow.hide()
                globals.currentWindow = self.window
                self.window.show()
                dlg.setWindowTitle("SUCCESS!")
                message = QLabel("MESSAGE SENT!")

            except:
                dlg.setWindowTitle("PASSWORD ERROR!")
                message = QLabel("WRONG PASSWORD!")
            dlg.layout.addWidget(message)
            dlg.layout.addWidget(dlg.buttonBox)
            dlg.setLayout(dlg.layout)
            dlg.exec()
         




from keySelection import Ui_Form as keySelectionUI
from sendMessage1 import Ui_Form as sendMessageUI
from home import Ui_Form as homeUI